# use this link to fetch more book information
# https://www.googleapis.com/books/v1/volumes?q=[pass in the name of the book]


# Create a new book
POST http://localhost:13700/books
Content-Type: application/json

{
   "title": "Black Beauty",
   "subtitle":	"High Interest Classics with Comprehension Activities",
   "authors": "Anna Sewell",
   "publisher": "EDCON Publishing Group",
   "publishedDate": "2003-07",
   "description":	"An abridged version of the story complete with vocabulary and comprehension checks for beginning readers. Divided into ten short chapters written using McGraw-Hill's Core Vocabulary and measured by the Fry Readability Formula, the workbook includes questions that test for comprehension, critical thinking, inference, recall of detail, and sequencing.",
   "industryIdentifiers":
      {
         "type": "ISBN_10",
         "identifier": "0931334519"
      }
   ,
   "pageCount": 137,
   "categories": ["Juvenile Fiction"],
   "bookCoverImageLinks": 
      {
         "thumbnail": "http://books.google.com/books/content?id=xu3bADLsheQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
      },
  "bookEdition": "This edition published in 2019 by Arcturus Publishing Limited 26/27 Bickels Yard, 151-153 Bermondsey Street, London SE1 3HA",
   "language": "en",
   "epub": {
    "isAvailable": false
  },
  "pdf": {
    "isAvailable": true,
    "downloadLink": "http://pinkmonkey.com/dl/library1/digi105.pdf"
  }
}

# Get all books
###
GET http://localhost:13700/books


# Update a book
###
PUT http://localhost:13700/books/601c2948368f4e47fcfb4135


# Delete a book
###
DELETE http://localhost:13700/books/601c4a03799d95064b393390


# Register a Customer
###
POST http://localhost:13700/register
Content-Type: application/json

{
   "firstName": "Mary",
   "lastName": "Smith",
   "email": "mary@gmail.com",
   "password": "123456"
}


# Get all customers
###
GET http://localhost:13700/customers



### Login Customer
POST http://localhost:13700/login
Content-Type: application/json

{
   "email": "mary@gmail.com",
   "password": "123456"
}